# codec probing

# headset codecs

If.rt5682 {
	Condition {
		Type String
		String1 "$${sys:bus/i2c/devices/i2c-10EC5682:00/modalias}"
		String2 "acpi:10EC5682:"
	}
	True.Define.rt5682 y
}

If.rt5682s {
	Condition {
		Type String
		String1 "$${sys:bus/i2c/devices/i2c-RTL5682:00/modalias}"
		String2 "acpi:RTL5682:"
	}
	True.Define.rt5682s y
}

# speaker amp

If.max98360a {
	Condition {
		Type String
		String1 "$${sys:bus/platform/devices/MX98360A:00/modalias}"
		String2 "acpi:MX98360A:"
	}
	True.Define.max98360a y
}
